apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        # FIXED: Pointing directly to your active AWS ECR Registry URL
        image: 606030504453.dkr.ecr.ap-south-1.amazonaws.com/backend:latest 
        
        # FIXED: Forces AWS EKS to pull down the freshly built image from ECR
        imagePullPolicy: Always 
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: mongodb://mongo-service:27017/luxeshop
        - name: JWT_SECRET
          value: luxeshop_super_secret_jwt_key
        - name: PORT
          value: "5000"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20