apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        # FIXED: Pointing directly to your active AWS ECR Registry URL
        image: 606030504453.dkr.ecr.ap-south-1.amazonaws.com/frontend:latest
        
        # FIXED: Forces AWS EKS to pull down the freshly built image from ECR
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"